main: fr.uracraft.urasyncro.UraSyncro

name: UraSyncro

description: Plugin de syncronisation.

author: Birdo

version: 1.0

api-version: 1.12

commands:
  urasyncro:
    description: Check if the plugin run correctly